import { type ReactNode, useEffect, useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Route, Switch, useLocation, Router as WouterRouter } from 'wouter';
import { ArrowDown, ArrowRight, Check, ChevronLeft, ChevronRight, Clock3, Instagram, MapPin, Menu, Phone, Sparkles, Star, X } from 'lucide-react';

const queryClient = new QueryClient();

type Dish = { name: string; detail: string; price: string; image: string; tag?: string };
const dishes: Dish[] = [
  { name: 'Coconut Prawn Curry', detail: 'Tiger prawns, green coconut, curry leaf, steamed rice', price: 'Rs 2,450', image: '/images/hero-prawns.jpg', tag: "Chef's pick" },
  { name: 'Hawaii Seafood Platter', detail: 'Lobster, grilled fish, prawns, mango-lime salsa', price: 'Rs 3,000', image: '/images/seafood-platter.jpg', tag: 'For sharing' },
  { name: 'Sunset Spritz', detail: 'Pineapple, citrus, basil, sparkling water', price: 'Rs 850', image: '/images/cocktail.jpg', tag: 'Zero-proof' },
];

function useReveal() {
  useEffect(() => {
    const items = document.querySelectorAll<HTMLElement>('.reveal');
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) { entry.target.classList.add('in-view'); observer.unobserve(entry.target); }
    }), { threshold: .12 });
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, []);
}

function Mark({ light = false }: { light?: boolean }) {
  return (
    <a href="#top" data-testid="link-brand" className={`flex items-center gap-3 focus-ring ${light ? 'text-[#fff8e9]' : 'text-[#163f42]'}`}>
      <span className="grid h-11 w-11 place-items-center rounded-full border-2 border-current font-display text-xl italic">H</span>
      <span className="leading-none"><strong className="block font-display text-[1.45rem] font-semibold tracking-tight">Cafe Hawaii</strong><small className="eyebrow opacity-70">Karachi · Est. 2016</small></span>
    </a>
  );
}

function Button({ children, onClick, href, variant = 'coral', testId }: { children: ReactNode; onClick?: () => void; href?: string; variant?: 'coral' | 'outline' | 'cream'; testId: string }) {
  const cls = `focus-ring inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-[.74rem] font-bold uppercase tracking-[.14em] transition-all duration-300 hover:-translate-y-0.5 ${variant === 'coral' ? 'bg-[#ef725f] text-[#fff8e9] hover:bg-[#df5f4d]' : variant === 'cream' ? 'bg-[#fff8e9] text-[#163f42] hover:bg-[#f8d47a]' : 'border border-current text-current hover:bg-current hover:text-[#fff8e9]'}`;
  if (href) return <a href={href} className={cls} data-testid={testId}>{children}</a>;
  return <button type="button" onClick={onClick} className={cls} data-testid={testId}>{children}</button>;
}

function ReservationModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [submitted, setSubmitted] = useState(false);
  if (!open) return null;
  return (
    <div className="modal-backdrop fixed inset-0 z-[60] grid place-items-center bg-[#163f42]/75 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="reserve-title">
      <div className="modal-card relative w-full max-w-lg rounded-[2rem] bg-[#fff8e9] p-6 text-[#163f42] shadow-2xl sm:p-9">
        <button type="button" onClick={onClose} className="focus-ring absolute right-5 top-5 grid h-9 w-9 place-items-center rounded-full bg-[#f2e9d6] transition hover:bg-[#f8d47a]" aria-label="Close reservation form" data-testid="button-close-reservation"><X size={18} /></button>
        {!submitted ? <><p className="eyebrow text-[#ef725f]">A table in the warm light</p><h2 id="reserve-title" className="font-display mt-3 text-4xl">Reserve your evening.</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#426266]">Tell us when to set the table. We’ll call to confirm your reservation shortly.</p>
          <form className="mt-7 grid gap-4" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); }}>
            <div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold uppercase tracking-wider">Your name<input required data-testid="input-reservation-name" className="rounded-xl border border-[#d9cfbc] bg-[#fffdf6] px-4 py-3 font-sans text-sm outline-none focus:border-[#ef725f]" placeholder="Ayesha Khan" /></label><label className="grid gap-2 text-xs font-bold uppercase tracking-wider">Phone number<input required type="tel" data-testid="input-reservation-phone" className="rounded-xl border border-[#d9cfbc] bg-[#fffdf6] px-4 py-3 font-sans text-sm outline-none focus:border-[#ef725f]" placeholder="0300 0000000" /></label></div>
            <div className="grid gap-4 sm:grid-cols-3"><label className="grid gap-2 text-xs font-bold uppercase tracking-wider">Date<input required type="date" data-testid="input-reservation-date" className="rounded-xl border border-[#d9cfbc] bg-[#fffdf6] px-3 py-3 text-sm outline-none focus:border-[#ef725f]" /></label><label className="grid gap-2 text-xs font-bold uppercase tracking-wider">Time<select data-testid="select-reservation-time" className="rounded-xl border border-[#d9cfbc] bg-[#fffdf6] px-3 py-3 text-sm outline-none focus:border-[#ef725f]"><option>7:00 pm</option><option>8:00 pm</option><option>9:00 pm</option></select></label><label className="grid gap-2 text-xs font-bold uppercase tracking-wider">Guests<select data-testid="select-reservation-guests" className="rounded-xl border border-[#d9cfbc] bg-[#fffdf6] px-3 py-3 text-sm outline-none focus:border-[#ef725f]"><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>5+ guests</option></select></label></div>
            <label className="grid gap-2 text-xs font-bold uppercase tracking-wider">A note for the kitchen <textarea data-testid="textarea-reservation-note" className="min-h-20 resize-none rounded-xl border border-[#d9cfbc] bg-[#fffdf6] px-4 py-3 text-sm outline-none focus:border-[#ef725f]" placeholder="Birthday, window table, dietary note..." /></label>
            <button type="submit" className="mt-2 rounded-full bg-[#ef725f] px-5 py-3.5 text-xs font-bold uppercase tracking-[.15em] text-[#fff8e9] transition hover:bg-[#df5f4d]" data-testid="button-submit-reservation">Request my table <ArrowRight size={16} /></button>
          </form></> :
          <div className="grid place-items-center py-12 text-center"><span className="grid h-16 w-16 place-items-center rounded-full bg-[#dbe9d4] text-[#477348]"><Check size={30} /></span><h2 className="font-display mt-6 text-4xl">We’ve got you.</h2><p className="mt-3 max-w-xs text-sm leading-6 text-[#426266]">Your request is on its way. Our host will call you at the number you shared to confirm.</p><button onClick={onClose} className="mt-7 rounded-full bg-[#163f42] px-6 py-3 text-xs font-bold uppercase tracking-[.15em] text-[#fff8e9]" data-testid="button-finish-reservation">Back to Cafe Hawaii</button></div>}
      </div>
    </div>
  );
}

function Header({ onReserve }: { onReserve: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const links = [['The story', '#story'], ['Menu', '#menu'], ['Moments', '#moments'], ['Visit us', '#visit']];
  return <header className="absolute left-0 right-0 top-0 z-30 text-[#fff8e9]"><div className="container-wide flex items-center justify-between py-5"><Mark light /><nav className="hidden items-center gap-8 lg:flex">{links.map(([label, href]) => <a key={href} href={href} className="nav-link focus-ring text-xs font-semibold uppercase tracking-[.15em]" data-testid={`link-nav-${label.toLowerCase().replace(' ', '-')}`}>{label}</a>)}<Button onClick={onReserve} variant="cream" testId="button-nav-reserve">Reserve a table</Button></nav><button type="button" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)} className="focus-ring grid h-11 w-11 place-items-center rounded-full border border-[#fff8e9]/40 lg:hidden" data-testid="button-mobile-menu">{menuOpen ? <X /> : <Menu />}</button></div>
    {menuOpen && <div className="mx-3 rounded-2xl bg-[#163f42] p-5 shadow-xl lg:hidden"><nav className="grid gap-1">{links.map(([label, href]) => <a onClick={() => setMenuOpen(false)} key={href} href={href} className="rounded-xl px-4 py-3 text-sm font-semibold uppercase tracking-wider hover:bg-[#28575a]" data-testid={`link-mobile-${label.toLowerCase().replace(' ', '-')}`}>{label}</a>)}<button onClick={() => { setMenuOpen(false); onReserve(); }} className="mt-3 rounded-full bg-[#ef725f] px-4 py-3 text-xs font-bold uppercase tracking-wider" data-testid="button-mobile-reserve">Reserve a table</button></nav></div>}
  </header>;
}

function Hero({ onReserve }: { onReserve: () => void }) {
  return <section id="top" className="relative flex min-h-[760px] items-end overflow-hidden bg-[#163f42] text-[#fff8e9] sm:min-h-[820px]"><img className="hero-image absolute inset-0 h-full w-full object-cover opacity-75" src="/images/cafe-interior.jpg" alt="Warmly lit Cafe Hawaii dining room" /><div className="hero-grid absolute inset-0" /><div className="absolute -right-20 top-36 hidden h-72 w-72 rounded-full border border-[#f8d47a]/40 lg:block float-ring" /><div className="container-wide relative pb-20 pt-40 sm:pb-28"><div className="max-w-3xl hero-copy"><p className="eyebrow reveal text-[#f8d47a]">A continental kitchen · Gulshan-e-Iqbal</p><h1 className="reveal delay-1 font-display mt-5 max-w-4xl text-[clamp(4rem,10vw,8.8rem)] font-medium leading-[.88] tracking-[-.045em]">We Serve<br /><i className="text-[#f8d47a]">Passion.</i></h1><p className="reveal delay-2 mt-7 max-w-md text-base leading-7 text-[#fff8e9]/80 sm:text-lg">A laid-back Aloha state of mind, poured into every plate. Step off Karachi’s streets and into our warm island evening.</p><div className="reveal delay-3 mt-9 flex flex-wrap gap-3"><Button onClick={onReserve} variant="coral" testId="button-hero-reserve">Reserve a table <ArrowRight size={16} /></Button><Button href="#menu" variant="outline" testId="link-hero-menu">Explore the menu <ArrowDown size={16} /></Button></div></div><div className="mt-20 flex items-end justify-between border-t border-[#fff8e9]/25 pt-5 text-xs text-[#fff8e9]/70 sm:mt-28"><span>Plot C-102, Block 4<br />Gulshan-e-Iqbal, Karachi</span><a href="#visit" className="hidden items-center gap-2 sm:flex" data-testid="link-hero-visit"><MapPin size={14} className="text-[#f8d47a]" /> Find your way to us</a><span className="text-right">Open daily<br /><b className="text-[#f8d47a]">12:00 pm — 11:30 pm</b></span></div></div></section>;
}

function Story() {
  return <section id="story" className="section-pad bg-[#fff8e9]"><div className="container-wide grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div className="reveal relative pl-8 sm:pl-12"><div className="absolute -left-3 top-12 h-52 w-44 rounded-[3rem] bg-[#f8d47a] sm:h-72 sm:w-60" /><div className="relative aspect-[4/5] max-w-md overflow-hidden rounded-[12rem_12rem_1.5rem_1.5rem] image-zoom"><img src="/images/hero-prawns.jpg" alt="Coconut prawn curry plated at Cafe Hawaii" className="h-full w-full object-cover" /><div className="absolute bottom-5 left-5 rounded-full bg-[#fff8e9]/90 px-4 py-2 text-xs font-bold uppercase tracking-wider text-[#163f42]">From our kitchen</div></div><div className="absolute -bottom-6 -right-3 grid h-24 w-24 place-items-center rounded-full bg-[#ef725f] text-center text-[.65rem] font-bold uppercase tracking-wider text-[#fff8e9] sm:-right-12"><span className="block">Made with<br />heart</span></div></div><div className="reveal delay-1"><p className="eyebrow text-[#ef725f]">The Cafe Hawaii story</p><h2 className="font-display mt-5 max-w-xl text-5xl leading-[.98] tracking-[-.03em] text-[#163f42] sm:text-7xl">Mastering the art of <i>food.</i></h2><p className="mt-7 max-w-lg text-base leading-8 text-[#426266]">We believe a great meal should make the world feel a little softer. Our kitchen brings continental craft, tropical instinct and Karachi’s generous spirit to the same table.</p><p className="mt-4 max-w-lg text-base leading-8 text-[#426266]">Come for the familiar. Stay for the unexpected: a bright squeeze of lime, a warm plate passed around, another story told over dinner.</p><a href="#visit" className="mt-8 inline-flex items-center gap-3 border-b-2 border-[#ef725f] pb-2 text-xs font-bold uppercase tracking-[.15em] text-[#163f42] transition hover:gap-5" data-testid="link-story-visit">Meet us in Gulshan <ArrowRight size={16} className="text-[#ef725f]" /></a></div></div></section>;
}

function Marquee() { return <div className="overflow-hidden bg-[#f8d47a] py-4 text-[#163f42]"><div className="marquee-track flex w-max items-center gap-8 whitespace-nowrap font-display text-2xl italic"><span>Good food, good mood</span><Sparkles className="text-[#ef725f]" size={19} /><span>Aloha in the city</span><Sparkles className="text-[#ef725f]" size={19} /><span>Stay for one more</span><Sparkles className="text-[#ef725f]" size={19} /><span>Good food, good mood</span><Sparkles className="text-[#ef725f]" size={19} /><span>Aloha in the city</span></div></div>; }

function MenuSection({ onReserve }: { onReserve: () => void }) {
  const [active, setActive] = useState(0);
  return <section id="menu" className="section-pad bg-[#e5eee4]"><div className="container-wide"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div className="reveal"><p className="eyebrow text-[#ef725f]">A taste of Hawaii</p><h2 className="font-display mt-4 text-5xl leading-none text-[#163f42] sm:text-7xl">On the table</h2></div><div className="reveal delay-1 max-w-sm text-sm leading-6 text-[#426266]">Thoughtful plates, sunny cocktails and the kind of food that makes conversation linger. <b className="text-[#163f42]">Rs 2,000–3,000 per person.</b></div></div><div className="mt-12 grid gap-5 md:grid-cols-3">{dishes.map((dish, i) => <article key={dish.name} className={`reveal delay-${i + 1} group ${i === active ? '' : 'md:translate-y-6'}`} onMouseEnter={() => setActive(i)} data-testid={`card-dish-${i}`}><div className="image-zoom relative aspect-[1.03] overflow-hidden rounded-[1.4rem] bg-[#d5dfd1]"><img src={dish.image} alt={dish.name} className="h-full w-full object-cover" /><span className="absolute left-4 top-4 rounded-full bg-[#fff8e9]/90 px-3 py-1.5 text-[.62rem] font-bold uppercase tracking-wider text-[#163f42]">{dish.tag}</span><button type="button" onClick={onReserve} className="absolute bottom-4 right-4 grid h-11 w-11 translate-y-2 place-items-center rounded-full bg-[#ef725f] text-[#fff8e9] opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100" aria-label={`Reserve a table for ${dish.name}`} data-testid={`button-dish-reserve-${i}`}><ArrowRight size={18} /></button></div><div className="flex items-start justify-between gap-3 pt-5"><div><h3 className="font-display text-2xl text-[#163f42]">{dish.name}</h3><p className="mt-1 text-sm leading-5 text-[#426266]">{dish.detail}</p></div><span className="shrink-0 pt-1 text-sm font-bold text-[#ef725f]">{dish.price}</span></div></article>)}</div><div className="mt-14 flex flex-col items-center justify-between gap-5 border-t border-[#bfd0c1] pt-6 sm:flex-row"><span className="text-sm text-[#426266]">More to discover, depending on the day’s best catch.</span><Button onClick={onReserve} variant="coral" testId="button-menu-reserve">Book your table <ArrowRight size={16} /></Button></div></div></section>;
}

function Gallery() {
  const [selected, setSelected] = useState<number | null>(null);
  const images = [{ src: '/images/cafe-interior.jpg', alt: 'Cafe Hawaii interior at evening' }, { src: '/images/seafood-platter.jpg', alt: 'Fresh seafood platter' }, { src: '/images/cocktail.jpg', alt: 'Sunset cocktail at the bar' }, { src: '/images/hero-prawns.jpg', alt: 'Grilled prawns with coconut rice' }];
  return <section id="moments" className="section-pad bg-[#163f42] text-[#fff8e9]"><div className="container-wide"><div className="flex items-end justify-between gap-4"><div className="reveal"><p className="eyebrow text-[#f8d47a]">Take a little Hawaii home</p><h2 className="font-display mt-4 text-5xl leading-none sm:text-7xl">The good<br /><i className="text-[#f8d47a]">moments.</i></h2></div><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" className="hidden items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#f8d47a] transition hover:text-[#fff8e9] sm:flex" data-testid="link-instagram"><Instagram size={18} /> @cafehawaiikarachi</a></div><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-5">{images.map((image, i) => <button key={image.src} type="button" onClick={() => setSelected(i)} className={`reveal image-zoom overflow-hidden rounded-2xl text-left ${i === 0 ? 'col-span-2 row-span-2 aspect-square sm:col-span-2 sm:aspect-auto' : 'aspect-square'}`} data-testid={`button-gallery-${i}`}><img src={image.src} alt={image.alt} className="h-full w-full object-cover" /></button>)}</div><div className="mt-8 flex items-center justify-between border-t border-[#fff8e9]/20 pt-5 text-sm text-[#fff8e9]/65"><span>15K+ friends on Instagram</span><span>Tag your table <b className="text-[#f8d47a]">#CafeHawaiiKarachi</b></span></div></div>{selected !== null && <div className="modal-backdrop fixed inset-0 z-[55] grid place-items-center bg-[#163f42]/90 p-5" role="dialog" aria-label="Gallery image"><button onClick={() => setSelected(null)} className="focus-ring absolute right-5 top-5 grid h-11 w-11 place-items-center rounded-full border border-[#fff8e9]/30 text-[#fff8e9]" aria-label="Close gallery" data-testid="button-close-gallery"><X /></button><button onClick={() => setSelected((selected + images.length - 1) % images.length)} className="focus-ring absolute left-4 grid h-11 w-11 place-items-center rounded-full border border-[#fff8e9]/30 text-[#fff8e9] sm:left-10" aria-label="Previous image" data-testid="button-gallery-previous"><ChevronLeft /></button><img src={images[selected].src} alt={images[selected].alt} className="max-h-[80vh] max-w-[82vw] rounded-2xl object-contain shadow-2xl" /><button onClick={() => setSelected((selected + 1) % images.length)} className="focus-ring absolute right-4 grid h-11 w-11 place-items-center rounded-full border border-[#fff8e9]/30 text-[#fff8e9] sm:right-10" aria-label="Next image" data-testid="button-gallery-next"><ChevronRight /></button></div>}</section>;
}

function SocialProof() {
  return <section className="bg-[#ef725f] py-14 text-[#fff8e9]"><div className="container-wide grid gap-8 md:grid-cols-[1fr_auto_1fr] md:items-center"><div className="reveal"><p className="eyebrow text-[#f8d47a]">The word on the street</p><p className="font-display mt-3 text-3xl leading-tight sm:text-4xl">“The kind of place<br />you want to keep secret.”</p></div><div className="reveal delay-1 flex items-center gap-4 md:border-x md:border-[#fff8e9]/30 md:px-12"><Star className="fill-[#f8d47a] text-[#f8d47a]" size={28} /><div><p className="font-display text-5xl">4.4</p><p className="text-xs uppercase tracking-widest text-[#fff8e9]/75">Google rating</p></div></div><div className="reveal delay-2 md:pl-8"><p className="text-sm leading-7 text-[#fff8e9]/85">More than 1,000 people have pulled up a chair, stayed for dessert and told a friend. That’s our favorite kind of review.</p><a href="https://www.google.com/maps/search/Cafe+Hawaii+Karachi" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#f8d47a]" data-testid="link-google-reviews">Read our reviews <ArrowRight size={15} /></a></div></div></section>;
}

function Visit({ onReserve }: { onReserve: () => void }) {
  return <section id="visit" className="section-pad bg-[#fff8e9]"><div className="container-wide grid gap-12 lg:grid-cols-[1fr_.9fr] lg:gap-24"><div className="reveal"><p className="eyebrow text-[#ef725f]">Come find us</p><h2 className="font-display mt-4 text-5xl leading-none text-[#163f42] sm:text-7xl">Your table<br /><i>is waiting.</i></h2><div className="mt-10 grid gap-7"><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#e5eee4] text-[#ef725f]"><MapPin size={18} /></span><div><p className="font-bold text-[#163f42]">Cafe Hawaii</p><p className="mt-1 max-w-xs text-sm leading-6 text-[#426266]">Plot C-102, Block 4, Gulshan-e-Iqbal, Karachi</p><a href="https://maps.google.com/?q=Cafe+Hawaii+Karachi" target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold uppercase tracking-wider text-[#ef725f]" data-testid="link-directions">Get directions <ArrowRight size={14} className="inline" /></a></div></div><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#e5eee4] text-[#ef725f]"><Clock3 size={18} /></span><div><p className="font-bold text-[#163f42]">Open daily</p><p className="mt-1 text-sm text-[#426266]">12:00 pm — 11:30 pm</p><p className="mt-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#477348]"><span className="h-2 w-2 rounded-full bg-[#70a66e]" /> Open now</p></div></div><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#e5eee4] text-[#ef725f]"><Phone size={18} /></span><div><p className="font-bold text-[#163f42]">Make it a plan</p><p className="mt-1 text-sm leading-6 text-[#426266]"><a href="tel:02134980002" className="hover:text-[#ef725f]" data-testid="link-phone-1">021-34980002</a> · <a href="tel:02134980003" className="hover:text-[#ef725f]" data-testid="link-phone-2">021-34980003</a><br /><a href="tel:03091358888" className="hover:text-[#ef725f]" data-testid="link-phone-3">0309-1358888</a></p></div></div></div><Button onClick={onReserve} variant="coral" testId="button-visit-reserve">Reserve a table <ArrowRight size={16} /></Button></div><div className="reveal delay-1 relative min-h-[380px] overflow-hidden rounded-[2rem] bg-[#e5eee4] sm:min-h-[510px]"><img src="/images/cafe-interior.jpg" alt="A warm corner of Cafe Hawaii" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#163f42]/70 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6 flex items-end justify-between text-[#fff8e9]"><span className="font-display text-2xl italic">See you by sunset.</span><span className="grid h-12 w-12 place-items-center rounded-full border border-[#fff8e9]/50"><MapPin size={19} /></span></div></div></div></section>;
}

function Footer() {
  const [email, setEmail] = useState(''); const [sent, setSent] = useState(false);
  return <footer className="bg-[#163f42] text-[#fff8e9]"><div className="container-wide grid gap-12 py-16 md:grid-cols-[1.1fr_.7fr_1fr]"><div><Mark light /><p className="mt-6 max-w-xs text-sm leading-7 text-[#fff8e9]/65">An island state of mind, in the heart of Gulshan. Good food, warm light, no rush.</p></div><div><p className="eyebrow text-[#f8d47a]">Explore</p><nav className="mt-5 grid gap-3 text-sm text-[#fff8e9]/75"><a href="#story" className="hover:text-[#f8d47a]" data-testid="link-footer-story">Our story</a><a href="#menu" className="hover:text-[#f8d47a]" data-testid="link-footer-menu">The menu</a><a href="#moments" className="hover:text-[#f8d47a]" data-testid="link-footer-moments">Moments</a><a href="#visit" className="hover:text-[#f8d47a]" data-testid="link-footer-visit">Find us</a></nav></div><div><p className="eyebrow text-[#f8d47a]">A little note from us</p><p className="mt-4 max-w-sm text-sm leading-6 text-[#fff8e9]/70">New dishes, special nights and reasons to come hungry. Straight to your inbox, never too often.</p>{sent ? <p className="mt-5 flex items-center gap-2 text-sm text-[#f8d47a]" data-testid="status-newsletter-success"><Check size={16} /> You’re on the list. See you soon.</p> : <form className="mt-5 flex max-w-sm border-b border-[#fff8e9]/40 pb-2" onSubmit={(e) => { e.preventDefault(); if (email) setSent(true); }}><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Your email address" aria-label="Email address" className="min-w-0 flex-1 bg-transparent py-2 text-sm text-[#fff8e9] outline-none placeholder:text-[#fff8e9]/45" data-testid="input-newsletter-email" /><button type="submit" className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#f8d47a]" data-testid="button-newsletter-submit">Join <ArrowRight size={15} /></button></form>}</div></div><div className="container-wide flex flex-col justify-between gap-3 border-t border-[#fff8e9]/15 py-5 text-xs text-[#fff8e9]/50 sm:flex-row"><span>© 2024 Cafe Hawaii. Made for long evenings.</span><span>15K+ Instagram · 8.6K+ Facebook</span></div></footer>;
}

function Home() {
  const [reserveOpen, setReserveOpen] = useState(false);
  useReveal();
  return <div className="grain site-shell"><Header onReserve={() => setReserveOpen(true)} /><main><Hero onReserve={() => setReserveOpen(true)} /><Marquee /><Story /><MenuSection onReserve={() => setReserveOpen(true)} /><Gallery /><SocialProof /><Visit onReserve={() => setReserveOpen(true)} /></main><Footer /><ReservationModal open={reserveOpen} onClose={() => setReserveOpen(false)} /><a href="#top" className="focus-ring fixed bottom-5 right-5 z-40 grid h-11 w-11 place-items-center rounded-full bg-[#f8d47a] text-[#163f42] shadow-lg transition hover:-translate-y-1" aria-label="Back to top" data-testid="link-back-to-top"><ArrowDown size={17} className="rotate-180" /></a></div>;
}

function Router() {
  return <RoutedErrorBoundary><Switch><Route path="/" component={Home} /><Route component={NotFound} /></Switch></RoutedErrorBoundary>;
}

function RoutedErrorBoundary({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  return <ErrorBoundary resetKey={location}>{children}</ErrorBoundary>;
}

function App() {
  return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>;
}

export default App;